---
- name: Set Hostname with hostname command
  hostname:
    name: "{{ hostname }}"
  notify:
    - restart hostname
    - restart systemd-logind

- name: Re-gather facts
  action: setup
  when: ansible_hostname != fqdn

- name: Build hosts file (backups will be made)
  with_items:
    - "{{ ip_address }}"
    - 127.0.1.1
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ item }}\s'
    line: "{{ item }} {{ fqdn }} {{ hostname }}"
    state: present
    backup: yes
  when: item is defined
  notify:
    - restart hostname
    - restart systemd-logind
